CREATE DATABASE IF NOT EXISTS ecommerce;

CREATE TABLE ecommerce.orders
(
    order_id String,
    customer_id String,
    market_id String,
    store_id String,
    payment_id String,
    order_created_datetime String,
    order_last_modified_datetime String,
    order_total String,
    currency_name String,
    order_status String,
    order_tax String,
    order_shipping String,
    order_discount String,
    order_subtotal String,
    platform_commission_fees String,
    tax_rate String,
    refund_amount String,
    total_weight String,
    order_source String,
    sales_channel String,
    cart_token String,
    email String,
    store_employee_id String,
    order_cancel_datetime String,
    financial_status String,
    fulfillment_status String,
    cancel_reason String,
    shipping_address_id String,
    billing_address_id String,
    customer_language String,
    browser_ip String,
    referring_site String,
    order_tags String,
    order_notes String,
    business_order_flag String,
    expedited_shipping_order_flag String,
    prime_order_flag String,
    replacement_order_flag String,
    refund_flag String,
    taxes_included_flag String,
    notes String,
) ENGINE = MergeTree ORDER BY (order_id, customer_id, market_id, store_id, payment_id, order_created_datetime, order_last_modified_datetime, order_total, currency_name, order_status, order_tax, order_shipping, order_discount, order_subtotal, platform_commission_fees, tax_rate, refund_amount, total_weight, order_source, sales_channel, cart_token, email, store_employee_id, order_cancel_datetime, financial_status, fulfillment_status, cancel_reason, shipping_address_id, billing_address_id, customer_language, browser_ip, referring_site, order_tags, order_notes, business_order_flag, expedited_shipping_order_flag, prime_order_flag, replacement_order_flag, refund_flag, taxes_included_flag, notes);

CREATE TABLE ecommerce.order_line_items
(
    order_item_id String,
    order_id String,
    currency_name String,
    product_variant_store_id String,
    order_item_created_datetime String,
    order_item_last_modified_datetime String,
    order_item_price String,
    order_item_tax String,
    order_item_shipping String,
    order_item_discount String,
    order_item_subtotal String,
    order_item_quantity String,
    order_quantity_fulfilled String,
    product_cost String,
    order_item_status String,
    platform_commission_fees String,
    gift_card_flag String,
    shipped_item_flag String,
    refund_flag String,
) ENGINE = MergeTree ORDER BY (order_item_id, order_id, currency_name, product_variant_store_id, order_item_created_datetime, order_item_last_modified_datetime, order_item_price, order_item_tax, order_item_shipping, order_item_discount, order_item_subtotal, order_item_quantity, order_quantity_fulfilled, product_cost, order_item_status, platform_commission_fees, gift_card_flag, shipped_item_flag, refund_flag);

CREATE TABLE ecommerce.order_payments
(
    payment_id String,
    order_id String,
    payment_gateway_name String,
) ENGINE = MergeTree ORDER BY (payment_id, order_id, payment_gateway_name);

CREATE TABLE ecommerce.transactions
(
    transaction_id String,
    order_id String,
    transaction_datetime String,
    transaction_gateway String,
    transaction_source String,
    transaction_type String,
    transaction_status String,
    transaction_authorization String,
    currency_name String,
    transaction_amount String,
    avs_result_code String,
    credit_card_bin String,
    credit_card_company String,
    cvv_result_code String,
    transaction_created_datetime String,
) ENGINE = MergeTree ORDER BY (transaction_id, order_id, transaction_datetime, transaction_gateway, transaction_source, transaction_type, transaction_status, transaction_authorization, currency_name, transaction_amount, avs_result_code, credit_card_bin, credit_card_company, cvv_result_code, transaction_created_datetime);

CREATE TABLE ecommerce.fulfillments
(
    fulfillment_id String,
    order_id String,
    fulfillment_status String,
    fulfillment_location_id String,
    fulfillment_location String,
    customer_address_id String,
    shipment_status String,
    tracking_company String,
    tracking_number String,
    currency_name String,
    fulfillment_cost String,
    shipping_cost String,
    fulfillment_datetime String,
    estimated_arrival_date String,
    delivery_datetime String,
    fulfillment_created_datetime String,
    fulfullment_updated_datetime String,
) ENGINE = MergeTree ORDER BY (fulfillment_id, order_id, fulfillment_status, fulfillment_location_id, fulfillment_location, customer_address_id, shipment_status, tracking_company, tracking_number, currency_name, fulfillment_cost, shipping_cost, fulfillment_datetime, estimated_arrival_date, delivery_datetime, fulfillment_created_datetime, fulfullment_updated_datetime);

CREATE TABLE ecommerce.order_item_fulfillments
(
    order_item_fulfillment_id String,
    order_item_id String,
    fulfillment_id String,
    product_variant_id String,
    product_variant_sku String,
    order_item_quantity String,
    order_item_quantity_to_fulfill String,
    item_fulfillment_status String,
) ENGINE = MergeTree ORDER BY (order_item_fulfillment_id, order_item_id, fulfillment_id, product_variant_id, product_variant_sku, order_item_quantity, order_item_quantity_to_fulfill, item_fulfillment_status);

CREATE TABLE ecommerce.refunds
(
    refund_id String,
    order_id String,
    employee_id String,
    refund_datetime String,
    currency_name String,
    refund_amount String,
) ENGINE = MergeTree ORDER BY (refund_id, order_id, employee_id, refund_datetime, currency_name, refund_amount);

CREATE TABLE ecommerce.refund_line_items
(
    refund_line_item_id String,
    refund_id String,
    order_id String,
    order_item_id String,
    refund_item_quantity String,
    refund_amount String,
    refund_tax_amount String,
) ENGINE = MergeTree ORDER BY (refund_line_item_id, refund_id, order_id, order_item_id, refund_item_quantity, refund_amount, refund_tax_amount);

CREATE TABLE ecommerce.product_listings
(
    product_list_id String,
    product_variant_store_id String,
    market_id String,
    store_id String,
    product_price String,
    currency_name String,
    product_listing_created_datetime String,
    product_listing_last_modified_datetime String,
    product_listing_status String,
    product_listing_description String,
) ENGINE = MergeTree ORDER BY (product_list_id, product_variant_store_id, market_id, store_id, product_price, currency_name, product_listing_created_datetime, product_listing_last_modified_datetime, product_listing_status, product_listing_description);

CREATE TABLE ecommerce.products
(
    product_id String,
    product_name String,
    product_type String,
    product_tags String,
    supplier_id String,
    product_created_datetime String,
    product_modified_datetime String,
    product_status String,
    product_description String,
    product_category String,
    product_subcategory String,
    product_brand String,
    product_department String,
) ENGINE = MergeTree ORDER BY (product_id, product_name, product_type, product_tags, supplier_id, product_created_datetime, product_modified_datetime, product_status, product_description, product_category, product_subcategory, product_brand, product_department);

CREATE TABLE ecommerce.product_variants
(
    product_variant_id String,
    product_id String,
    supplier_id String,
    product_variant_name String,
    product_variant_sku String,
    product_variant_created_datetime String,
    product_variant_last_modified_datetime String,
    product_variant_color String,
    product_variant_size String,
    product_variant_weight String,
    product_variant_weight_unit String,
    product_variant_status String,
    barcode String,
    inventory_tracked_flag String,
    requires_shipping_flag String,
    country_of_origin String,
    image_url String,
    image_position String,
) ENGINE = MergeTree ORDER BY (product_variant_id, product_id, supplier_id, product_variant_name, product_variant_sku, product_variant_created_datetime, product_variant_last_modified_datetime, product_variant_color, product_variant_size, product_variant_weight, product_variant_weight_unit, product_variant_status, barcode, inventory_tracked_flag, requires_shipping_flag, country_of_origin, image_url, image_position);

CREATE TABLE ecommerce.inventory_history
(
    product_variant_store_id String,
    inventory_datetime String,
    store_id String,
    inventory_quantity String,
) ENGINE = MergeTree ORDER BY (product_variant_store_id, inventory_datetime, store_id, inventory_quantity);

CREATE TABLE ecommerce.price_history
(
    product_variant_store_id String,
    price_datetime String,
    price String,
    currency String,
    store_id String,
    market_id String,
    price_start_datetime String,
    price_end_datetime String,
) ENGINE = MergeTree ORDER BY (product_variant_store_id, price_datetime, price, currency, store_id, market_id, price_start_datetime, price_end_datetime);

CREATE TABLE ecommerce.stores
(
    store_id String,
    market_id String,
    location_name String,
    address1 String,
    address2 String,
    city String,
    state String,
    country String,
    zip String,
    phone_number String,
    store_open_date String,
    store_close_date String,
) ENGINE = MergeTree ORDER BY (store_id, market_id, location_name, address1, address2, city, state, country, zip, phone_number, store_open_date, store_close_date);

CREATE TABLE ecommerce.inventory_cost_history
(
    product_variant_store_id String,
    cost_datetime String,
    store_id String,
    cost String,
    currency String,
    received_datetime String,
    quantity_received String,
    supplier_id String,
) ENGINE = MergeTree ORDER BY (product_variant_store_id, cost_datetime, store_id, cost, currency, received_datetime, quantity_received, supplier_id);

CREATE TABLE ecommerce.collections
(
    collection_id String,
    product_variant_store_id String,
    store_id String,
    collection_created_datetime String,
    collection_last_modified_datetime String,
) ENGINE = MergeTree ORDER BY (collection_id, product_variant_store_id, store_id, collection_created_datetime, collection_last_modified_datetime);

CREATE TABLE ecommerce.product_variant_stores
(
    product_variant_store_id String,
    product_variant_id String,
    store_id String,
    product_variant_store_created_datetime String,
    product_variant_store_last_modified_datetime String,
) ENGINE = MergeTree ORDER BY (product_variant_store_id, product_variant_id, store_id, product_variant_store_created_datetime, product_variant_store_last_modified_datetime);

CREATE TABLE ecommerce.product_reviews
(
    review_id String,
    product_id String,
    customer_id String,
    review String,
    rating String,
    product_review_created_datetime String,
    product_review_last_modified_datetime String,
    review_status String,
    review_language String,
    review_market String,
) ENGINE = MergeTree ORDER BY (review_id, product_id, customer_id, review, rating, product_review_created_datetime, product_review_last_modified_datetime, review_status, review_language, review_market);

CREATE TABLE ecommerce.customers
(
    customer_id String,
    first_name String,
    last_name String,
    email String,
    address_id String,
    customer_status String,
    phone_number String,
    customer_created_datetime String,
    customer_last_modified_datetime String,
) ENGINE = MergeTree ORDER BY (customer_id, first_name, last_name, email, address_id, customer_status, phone_number, customer_created_datetime, customer_last_modified_datetime);

CREATE TABLE ecommerce.customer_addresses
(
    customer_address_id String,
    customer_id String,
    address1 String,
    address2 String,
    city String,
    state String,
    zip String,
    country String,
    address_type String,
    address_created_datetime String,
    address_last_modified_datetime String,
) ENGINE = MergeTree ORDER BY (customer_address_id, customer_id, address1, address2, city, state, zip, country, address_type, address_created_datetime, address_last_modified_datetime);

CREATE TABLE ecommerce.suppliers
(
    supplier_id String,
    supplier_name String,
    supplier_address String,
    supplier_city String,
    supplier_state String,
    supplier_zip String,
    supplier_country String,
    supplier_phone String,
    supplier_email String,
    supplier_status String,
    supplier_created_datetime String,
    supplier_last_modified_datetime String,
) ENGINE = MergeTree ORDER BY (supplier_id, supplier_name, supplier_address, supplier_city, supplier_state, supplier_zip, supplier_country, supplier_phone, supplier_email, supplier_status, supplier_created_datetime, supplier_last_modified_datetime);

CREATE TABLE ecommerce.audiences
(
    audience_id String,
    customer_id String,
    audience_created_datetime String,
    audience_last_modified_datetime String,
) ENGINE = MergeTree ORDER BY (audience_id, customer_id, audience_created_datetime, audience_last_modified_datetime);

CREATE TABLE ecommerce.ad_campaigns
(
    ad_campaign_id String,
    audience_id String,
    ad_platform_id String,
    ad_campaign_created_datetime String,
    ad_campaign_last_modified_datetime String,
) ENGINE = MergeTree ORDER BY (ad_campaign_id, audience_id, ad_platform_id, ad_campaign_created_datetime, ad_campaign_last_modified_datetime);

CREATE TABLE ecommerce.ads
(
    ad_id String,
    ad_campaign_id String,
    ad_created_datetime String,
    ad_last_modified_datetime String,
) ENGINE = MergeTree ORDER BY (ad_id, ad_campaign_id, ad_created_datetime, ad_last_modified_datetime);

CREATE TABLE ecommerce.ad_impressions
(
    ad_impression_id String,
    ad_id String,
    ad_impression_datetime String,
) ENGINE = MergeTree ORDER BY (ad_impression_id, ad_id, ad_impression_datetime);

CREATE TABLE ecommerce.email_campaigns
(
    email_campaign_id String,
    audience_id String,
    email_campaign_created_datetime String,
) ENGINE = MergeTree ORDER BY (email_campaign_id, audience_id, email_campaign_created_datetime);

CREATE TABLE ecommerce.emails
(
    email_id String,
    email_campaign_id String,
    email_created_datetime String,
) ENGINE = MergeTree ORDER BY (email_id, email_campaign_id, email_created_datetime);

CREATE TABLE ecommerce.emails_sent
(
    email_sent_id String,
    email_id String,
    email_sent_datetime String,
) ENGINE = MergeTree ORDER BY (email_sent_id, email_id, email_sent_datetime);

CREATE TABLE ecommerce.customer_email_addresses
(
    customer_email_address_id String,
    customer_id String,
    email_address String,
    email_address_created_datetime String,
    email_address_last_modified_datetime String,
) ENGINE = MergeTree ORDER BY (customer_email_address_id, customer_id, email_address, email_address_created_datetime, email_address_last_modified_datetime);

CREATE TABLE ecommerce.calendar
(
    date String,
    day_of_week String,
    month String,
    year String,
    fiscal_week String,
    fiscal_month String,
    fiscal_quarter String,
    fiscal_year String,
) ENGINE = MergeTree ORDER BY (date, day_of_week, month, year, fiscal_week, fiscal_month, fiscal_quarter, fiscal_year);

CREATE TABLE ecommerce.currency
(
    currency_name String,
    currency_date String,
    currency_exchange_rate String,
) ENGINE = MergeTree ORDER BY (currency_name, currency_date, currency_exchange_rate);

CREATE TABLE ecommerce.markets
(
    market_id String,
    market_name String,
) ENGINE = MergeTree ORDER BY (market_id, market_name);

CREATE TABLE ecommerce.store_markets
(
    store_market_id String,
    store_id String,
    market_id String,
) ENGINE = MergeTree ORDER BY (store_market_id, store_id, market_id);

CREATE TABLE ecommerce.product_suppliers
(
    product_supplier_id String,
    product_id String,
    supplier_id String,
    product_supplier_created_datetime String,
    product_supplier_last_modified_datetime String,
) ENGINE = MergeTree ORDER BY (product_supplier_id, product_id, supplier_id, product_supplier_created_datetime, product_supplier_last_modified_datetime);

CREATE TABLE ecommerce.households
(
    household_id String,
    customer_id String,
) ENGINE = MergeTree ORDER BY (household_id, customer_id);

CREATE TABLE ecommerce.employees
(
    employee_id String,
    store_employee_id String,
    first_name String,
    last_name String,
    employee_start_date String,
    employee_end_date String,
) ENGINE = MergeTree ORDER BY (employee_id, store_employee_id, first_name, last_name, employee_start_date, employee_end_date);

CREATE TABLE ecommerce.order_discounts
(
    order_discount_id String,
    order_id String,
    discount_code String,
    discount_type String,
    currency_name String,
    discount_amount String,
) ENGINE = MergeTree ORDER BY (order_discount_id, order_id, discount_code, discount_type, currency_name, discount_amount);

CREATE TABLE ecommerce.order_shipping_services
(
    order_shipping_line_id String,
    order_id String,
    order_item_id String,
    shipping_code String,
    shipping_title String,
    carrier_identifier String,
) ENGINE = MergeTree ORDER BY (order_shipping_line_id, order_id, order_item_id, shipping_code, shipping_title, carrier_identifier);

CREATE TABLE ecommerce.events_base_cart_viewed
(
    products String,
    total String,
    anonymous_id String,
    user_id String,
    original_timestamp String,
    context_ip String,
    context_source String,
    context_library_version String,
    context_library_name String,
    context_referrer String,
    context_page_title String,
    context_user_agent String,
    context_page_height String,
    context_debug String,
    context_page_referrer String,
    context_page_path String,
    context_os_name String,
    context_page_url String,
    context_locale String,
    context_timezone String,
    context_page_width String,
    context_campaign_name String,
    context_campaign_medium String,
    context_campaign_source String,
    context_page_search String,
    context_page_hash String,
    event_id String,
) ENGINE = MergeTree ORDER BY (products, total, anonymous_id, user_id, original_timestamp, context_ip, context_source, context_library_version, context_library_name, context_referrer, context_page_title, context_user_agent, context_page_height, context_debug, context_page_referrer, context_page_path, context_os_name, context_page_url, context_locale, context_timezone, context_page_width, context_campaign_name, context_campaign_medium, context_campaign_source, context_page_search, context_page_hash, event_id);

CREATE TABLE ecommerce.events_base_checkout_created
(
    affiliation String,
    coupon String,
    currency String,
    discount String,
    products String,
    tax String,
    value String,
    anonymous_id String,
    user_id String,
    original_timestamp String,
    context_library_name String,
    context_locale String,
    context_user_agent String,
    context_source String,
    context_library_version String,
    context_ip String,
    context_passed_ip String,
    event_id String,
) ENGINE = MergeTree ORDER BY (affiliation, coupon, currency, discount, products, tax, value, anonymous_id, user_id, original_timestamp, context_library_name, context_locale, context_user_agent, context_source, context_library_version, context_ip, context_passed_ip, event_id);

CREATE TABLE ecommerce.events_base_checkout_updated
(
    affiliation String,
    coupon String,
    currency String,
    discount String,
    products String,
    tax String,
    value String,
    anonymous_id String,
    user_id String,
    original_timestamp String,
    context_source String,
    context_locale String,
    context_user_agent String,
    context_library_name String,
    context_ip String,
    context_library_version String,
    context_passed_ip String,
    event_id String,
) ENGINE = MergeTree ORDER BY (affiliation, coupon, currency, discount, products, tax, value, anonymous_id, user_id, original_timestamp, context_source, context_locale, context_user_agent, context_library_name, context_ip, context_library_version, context_passed_ip, event_id);

CREATE TABLE ecommerce.events_base_identifies
(
    address_city String,
    address_street String,
    email String,
    first_name String,
    last_name String,
    name String,
    phone String,
    anonymous_id String,
    user_id String,
    external_customer_id String,
    created_at String,
    original_timestamp String,
    context_traits_first_name String,
    context_traits_phone String,
    context_locale String,
    context_library_name String,
    context_passed_ip String,
    context_user_agent String,
    context_ip String,
    context_source String,
    context_traits_email String,
    context_traits_last_name String,
    context_traits_created_at String,
    context_traits_external_customer_id String,
    context_library_version String,
    context_traits_name String,
    context_traits_context_session_id String,
    context_traits_address_street String,
    context_traits_context_ip String,
    context_traits_address_country_code String,
    context_traits_address_state String,
    context_traits_context_client_id String,
    context_traits_context_anonymous_id String,
    context_traits_address_postal_code String,
    context_traits_address_city String,
    context_traits_addresses String,
    context_traits_context_page_url String,
    context_page_path String,
    context_traits_context_page_search String,
    context_traits_context_debug String,
    context_traits_context_os_name String,
    context_traits_context_page_width String,
    context_page_width String,
    context_traits_context_page_title String,
    context_traits_context_page_referrer String,
    context_os_name String,
    context_referrer String,
    context_page_height String,
    context_traits_context_library_version String,
    context_page_search String,
    context_traits_context_locale String,
    context_traits_context_page_height String,
    context_traits_context_user_agent String,
    context_page_url String,
    context_timezone String,
    context_page_referrer String,
    context_traits_context_app String,
    context_traits_context_library_name String,
    context_page_title String,
    context_traits_context_referrer String,
    context_traits_context_initialized String,
    context_debug String,
    context_traits_context_timezone String,
    context_traits_context_page_path String,
    context_traits_context_offline String,
    context_campaign_gclid String,
    context_traits_context_campaign_gclid String,
    context_traits_context_page_hash String,
    context_page_hash String,
    context_campaign_term String,
    context_traits_context_campaign_source String,
    context_traits_context_campaign_term String,
    context_traits_context_campaign_medium String,
    context_campaign_name String,
    context_campaign_source String,
    context_traits_context_campaign_name String,
    context_campaign_medium String,
    context_campaign_profile String,
    context_campaign_id String,
    context_traits_context_campaign_id String,
    context_traits_context_campaign_profile String,
    context_campaign_content String,
    context_traits_context_campaign_content String,
    event_id String,
) ENGINE = MergeTree ORDER BY (address_city, address_street, email, first_name, last_name, name, phone, anonymous_id, user_id, external_customer_id, created_at, original_timestamp, context_traits_first_name, context_traits_phone, context_locale, context_library_name, context_passed_ip, context_user_agent, context_ip, context_source, context_traits_email, context_traits_last_name, context_traits_created_at, context_traits_external_customer_id, context_library_version, context_traits_name, context_traits_context_session_id, context_traits_address_street, context_traits_context_ip, context_traits_address_country_code, context_traits_address_state, context_traits_context_client_id, context_traits_context_anonymous_id, context_traits_address_postal_code, context_traits_address_city, context_traits_addresses, context_traits_context_page_url, context_page_path, context_traits_context_page_search, context_traits_context_debug, context_traits_context_os_name, context_traits_context_page_width, context_page_width, context_traits_context_page_title, context_traits_context_page_referrer, context_os_name, context_referrer, context_page_height, context_traits_context_library_version, context_page_search, context_traits_context_locale, context_traits_context_page_height, context_traits_context_user_agent, context_page_url, context_timezone, context_page_referrer, context_traits_context_app, context_traits_context_library_name, context_page_title, context_traits_context_referrer, context_traits_context_initialized, context_debug, context_traits_context_timezone, context_traits_context_page_path, context_traits_context_offline, context_campaign_gclid, context_traits_context_campaign_gclid, context_traits_context_page_hash, context_page_hash, context_campaign_term, context_traits_context_campaign_source, context_traits_context_campaign_term, context_traits_context_campaign_medium, context_campaign_name, context_campaign_source, context_traits_context_campaign_name, context_campaign_medium, context_campaign_profile, context_campaign_id, context_traits_context_campaign_id, context_traits_context_campaign_profile, context_campaign_content, context_traits_context_campaign_content, event_id);

CREATE TABLE ecommerce.events_base_logged_in
(
    anonymous_id String,
    user_id String,
    original_timestamp String,
    context_ip String,
    context_library_name String,
    context_source String,
    context_library_version String,
    context_page_width String,
    context_timezone String,
    context_user_agent String,
    context_page_url String,
    context_page_referrer String,
    context_os_name String,
    context_debug String,
    context_page_title String,
    context_page_height String,
    context_locale String,
    context_referrer String,
    context_page_path String,
    context_page_search String,
    event_id String,
) ENGINE = MergeTree ORDER BY (anonymous_id, user_id, original_timestamp, context_ip, context_library_name, context_source, context_library_version, context_page_width, context_timezone, context_user_agent, context_page_url, context_page_referrer, context_os_name, context_debug, context_page_title, context_page_height, context_locale, context_referrer, context_page_path, context_page_search, event_id);

CREATE TABLE ecommerce.events_base_order_cancelled
(
    billing_address_address String,
    billing_address_city String,
    billing_address_country String,
    billing_address_first_name String,
    billing_address_last_name String,
    billing_address_postal_code String,
    billing_address_state String,
    currency String,
    order_id String,
    revenue String,
    shipping String,
    status String,
    subtotal String,
    total String,
    type String,
    value String,
    anonymous_id String,
    user_id String,
    original_timestamp String,
    context_library_name String,
    context_source String,
    context_library_version String,
    context_ip String,
    context_passed_ip String,
    context_locale String,
    context_user_agent String,
    event_id String,
) ENGINE = MergeTree ORDER BY (billing_address_address, billing_address_city, billing_address_country, billing_address_first_name, billing_address_last_name, billing_address_postal_code, billing_address_state, currency, order_id, revenue, shipping, status, subtotal, total, type, value, anonymous_id, user_id, original_timestamp, context_library_name, context_source, context_library_version, context_ip, context_passed_ip, context_locale, context_user_agent, event_id);

CREATE TABLE ecommerce.events_base_order_completed
(
    affiliation String,
    billing_address_address String,
    billing_address_city String,
    billing_address_country String,
    billing_address_first_name String,
    billing_address_last_name String,
    billing_address_phone String,
    billing_address_postal_code String,
    billing_address_state String,
    cart_id String,
    coupon String,
    currency String,
    discount String,
    event_text String,
    order_id String,
    payment_type String,
    products String,
    revenue String,
    shipping String,
    status String,
    subtotal String,
    tax String,
    total String,
    type String,
    value String,
    anonymous_id String,
    user_id String,
    original_timestamp String,
    context_passed_ip String,
    context_user_agent String,
    context_source String,
    context_library_name String,
    context_library_version String,
    context_locale String,
    context_ip String,
    event_id String,
) ENGINE = MergeTree ORDER BY (affiliation, billing_address_address, billing_address_city, billing_address_country, billing_address_first_name, billing_address_last_name, billing_address_phone, billing_address_postal_code, billing_address_state, cart_id, coupon, currency, discount, event_text, order_id, payment_type, products, revenue, shipping, status, subtotal, tax, total, type, value, anonymous_id, user_id, original_timestamp, context_passed_ip, context_user_agent, context_source, context_library_name, context_library_version, context_locale, context_ip, event_id);

CREATE TABLE ecommerce.events_base_order_updated
(
    affiliation String,
    billing_address_address String,
    billing_address_city String,
    billing_address_country String,
    billing_address_first_name String,
    billing_address_last_name String,
    billing_address_phone String,
    billing_address_postal_code String,
    billing_address_state String,
    cart_id String,
    coupon String,
    currency String,
    discount String,
    event_text String,
    order_id String,
    payment_type String,
    products String,
    revenue String,
    shipping String,
    status String,
    subtotal String,
    tax String,
    total String,
    type String,
    value String,
    anonymous_id String,
    user_id String,
    original_timestamp String,
    context_user_agent String,
    context_ip String,
    context_locale String,
    context_library_name String,
    context_passed_ip String,
    context_source String,
    context_library_version String,
    event_id String,
) ENGINE = MergeTree ORDER BY (affiliation, billing_address_address, billing_address_city, billing_address_country, billing_address_first_name, billing_address_last_name, billing_address_phone, billing_address_postal_code, billing_address_state, cart_id, coupon, currency, discount, event_text, order_id, payment_type, products, revenue, shipping, status, subtotal, tax, total, type, value, anonymous_id, user_id, original_timestamp, context_user_agent, context_ip, context_locale, context_library_name, context_passed_ip, context_source, context_library_version, event_id);

CREATE TABLE ecommerce.events_base_pages
(
    _hash String,
    height String,
    name String,
    path String,
    referrer String,
    search String,
    title String,
    url String,
    width String,
    anonymous_id String,
    user_id String,
    original_timestamp String,
    context_ip String,
    context_library_version String,
    context_library_name String,
    context_timezone String,
    context_page_hash String,
    context_page_search String,
    context_page_height String,
    context_locale String,
    context_page_url String,
    context_page_referrer String,
    context_campaign_medium String,
    context_campaign_name String,
    context_debug String,
    context_os_name String,
    context_referrer String,
    context_campaign_gclid String,
    context_page_title String,
    context_page_path String,
    context_user_agent String,
    context_campaign_term String,
    context_campaign_source String,
    context_page_width String,
    context_campaign_content String,
    context_campaign_profile String,
    context_campaign_id String,
    event_id String,
) ENGINE = MergeTree ORDER BY (_hash, height, name, path, referrer, search, title, url, width, anonymous_id, user_id, original_timestamp, context_ip, context_library_version, context_library_name, context_timezone, context_page_hash, context_page_search, context_page_height, context_locale, context_page_url, context_page_referrer, context_campaign_medium, context_campaign_name, context_debug, context_os_name, context_referrer, context_campaign_gclid, context_page_title, context_page_path, context_user_agent, context_campaign_term, context_campaign_source, context_page_width, context_campaign_content, context_campaign_profile, context_campaign_id, event_id);

CREATE TABLE ecommerce.events_base_product_added
(
    brand String,
    category String,
    image_url String,
    name String,
    position String,
    price String,
    product_id String,
    quantity String,
    sku String,
    url String,
    variant String,
    anonymous_id String,
    user_id String,
    original_timestamp String,
    context_library_name String,
    context_ip String,
    context_library_version String,
    context_source String,
    context_page_height String,
    context_page_path String,
    context_os_name String,
    context_debug String,
    context_locale String,
    context_page_url String,
    context_referrer String,
    context_page_search String,
    context_timezone String,
    context_user_agent String,
    context_page_referrer String,
    context_page_width String,
    context_page_title String,
    context_campaign_gclid String,
    context_campaign_content String,
    context_campaign_medium String,
    context_campaign_name String,
    context_campaign_source String,
    context_campaign_term String,
    context_page_hash String,
    context_campaign_profile String,
    context_campaign_id String,
    event_id String,
) ENGINE = MergeTree ORDER BY (brand, category, image_url, name, position, price, product_id, quantity, sku, url, variant, anonymous_id, user_id, original_timestamp, context_library_name, context_ip, context_library_version, context_source, context_page_height, context_page_path, context_os_name, context_debug, context_locale, context_page_url, context_referrer, context_page_search, context_timezone, context_user_agent, context_page_referrer, context_page_width, context_page_title, context_campaign_gclid, context_campaign_content, context_campaign_medium, context_campaign_name, context_campaign_source, context_campaign_term, context_page_hash, context_campaign_profile, context_campaign_id, event_id);

CREATE TABLE ecommerce.events_base_product_list_viewed
(
    category String,
    list_id String,
    products String,
    anonymous_id String,
    user_id String,
    original_timestamp String,
    context_source String,
    context_library_name String,
    context_ip String,
    context_library_version String,
    context_campaign_name String,
    context_page_title String,
    context_page_width String,
    context_campaign_medium String,
    context_timezone String,
    context_locale String,
    context_os_name String,
    context_page_referrer String,
    context_page_height String,
    context_page_search String,
    context_debug String,
    context_user_agent String,
    context_referrer String,
    context_page_url String,
    context_campaign_source String,
    context_page_path String,
    context_campaign_term String,
    context_campaign_gclid String,
    context_campaign_content String,
    context_page_hash String,
    context_campaign_profile String,
    context_campaign_id String,
    event_id String,
) ENGINE = MergeTree ORDER BY (category, list_id, products, anonymous_id, user_id, original_timestamp, context_source, context_library_name, context_ip, context_library_version, context_campaign_name, context_page_title, context_page_width, context_campaign_medium, context_timezone, context_locale, context_os_name, context_page_referrer, context_page_height, context_page_search, context_debug, context_user_agent, context_referrer, context_page_url, context_campaign_source, context_page_path, context_campaign_term, context_campaign_gclid, context_campaign_content, context_page_hash, context_campaign_profile, context_campaign_id, event_id);

CREATE TABLE ecommerce.events_base_product_removed
(
    position String,
    anonymous_id String,
    user_id String,
    original_timestamp String,
    context_ip String,
    context_library_name String,
    context_library_version String,
    context_source String,
    context_user_agent String,
    context_locale String,
    context_page_url String,
    context_page_path String,
    context_page_referrer String,
    context_page_title String,
    context_os_name String,
    context_debug String,
    context_referrer String,
    context_page_height String,
    context_timezone String,
    context_page_width String,
    event_id String,
) ENGINE = MergeTree ORDER BY (position, anonymous_id, user_id, original_timestamp, context_ip, context_library_name, context_library_version, context_source, context_user_agent, context_locale, context_page_url, context_page_path, context_page_referrer, context_page_title, context_os_name, context_debug, context_referrer, context_page_height, context_timezone, context_page_width, event_id);

CREATE TABLE ecommerce.events_base_products_searched
(
    query String,
    anonymous_id String,
    user_id String,
    original_timestamp String,
    context_source String,
    context_ip String,
    context_library_version String,
    context_library_name String,
    context_page_search String,
    context_os_name String,
    context_locale String,
    context_referrer String,
    context_page_referrer String,
    context_page_height String,
    context_timezone String,
    context_page_title String,
    context_page_path String,
    context_page_url String,
    context_user_agent String,
    context_debug String,
    context_page_width String,
    event_id String,
) ENGINE = MergeTree ORDER BY (query, anonymous_id, user_id, original_timestamp, context_source, context_ip, context_library_version, context_library_name, context_page_search, context_os_name, context_locale, context_referrer, context_page_referrer, context_page_height, context_timezone, context_page_title, context_page_path, context_page_url, context_user_agent, context_debug, context_page_width, event_id);

CREATE TABLE ecommerce.events_base_signed_up
(
    email String,
    first_name String,
    last_name String,
    anonymous_id String,
    user_id String,
    original_timestamp String,
    context_library_name String,
    context_library_version String,
    context_ip String,
    context_source String,
    context_timezone String,
    context_referrer String,
    context_os_name String,
    context_page_height String,
    context_user_agent String,
    context_locale String,
    context_debug String,
    context_page_referrer String,
    context_page_url String,
    context_page_width String,
    context_page_title String,
    context_page_path String,
    event_id String,
) ENGINE = MergeTree ORDER BY (email, first_name, last_name, anonymous_id, user_id, original_timestamp, context_library_name, context_library_version, context_ip, context_source, context_timezone, context_referrer, context_os_name, context_page_height, context_user_agent, context_locale, context_debug, context_page_referrer, context_page_url, context_page_width, context_page_title, context_page_path, event_id);

CREATE TABLE ecommerce.events_base_subscription_activated
(
    charge_interval_frequency String,
    created_at String,
    has_queued_charges String,
    is_skippable String,
    is_swappable String,
    max_retries_reached String,
    next_charge_scheduled_at String,
    order_billing_address_address String,
    order_billing_address_city String,
    order_billing_address_country String,
    order_billing_address_email String,
    order_billing_address_first_name String,
    order_billing_address_last_name String,
    order_billing_address_phone String,
    order_billing_address_postal_code String,
    order_billing_address_state String,
    order_coupon String,
    order_currency String,
    order_discount String,
    order_id String,
    order_interval_frequency String,
    order_interval_unit String,
    order_order_id String,
    order_products String,
    order_revenue String,
    order_status String,
    order_subtotal String,
    order_tax String,
    order_total String,
    order_type String,
    order_value String,
    products String,
    sku_override String,
    started_at String,
    status String,
    updated_at String,
    user_id String,
    original_timestamp String,
    context_source String,
    context_library_version String,
    context_ip String,
    context_library_name String,
    event_id String,
) ENGINE = MergeTree ORDER BY (charge_interval_frequency, created_at, has_queued_charges, is_skippable, is_swappable, max_retries_reached, next_charge_scheduled_at, order_billing_address_address, order_billing_address_city, order_billing_address_country, order_billing_address_email, order_billing_address_first_name, order_billing_address_last_name, order_billing_address_phone, order_billing_address_postal_code, order_billing_address_state, order_coupon, order_currency, order_discount, order_id, order_interval_frequency, order_interval_unit, order_order_id, order_products, order_revenue, order_status, order_subtotal, order_tax, order_total, order_type, order_value, products, sku_override, started_at, status, updated_at, user_id, original_timestamp, context_source, context_library_version, context_ip, context_library_name, event_id);

CREATE TABLE ecommerce.events_base_subscription_cancelled
(
    charge_interval_frequency String,
    created_at String,
    end_reason String,
    ended_at String,
    has_queued_charges String,
    is_skippable String,
    is_swappable String,
    max_retries_reached String,
    order_billing_address_address String,
    order_billing_address_city String,
    order_billing_address_country String,
    order_billing_address_email String,
    order_billing_address_first_name String,
    order_billing_address_last_name String,
    order_billing_address_phone String,
    order_billing_address_postal_code String,
    order_billing_address_state String,
    order_cart_id String,
    order_coupon String,
    order_currency String,
    order_discount String,
    order_id String,
    order_interval_frequency String,
    order_interval_unit String,
    order_order_id String,
    order_products String,
    order_revenue String,
    order_status String,
    order_subtotal String,
    order_tax String,
    order_total String,
    order_type String,
    order_value String,
    products String,
    sku_override String,
    started_at String,
    status String,
    updated_at String,
    user_id String,
    original_timestamp String,
    context_source String,
    context_library_name String,
    context_library_version String,
    context_ip String,
    event_id String,
) ENGINE = MergeTree ORDER BY (charge_interval_frequency, created_at, end_reason, ended_at, has_queued_charges, is_skippable, is_swappable, max_retries_reached, order_billing_address_address, order_billing_address_city, order_billing_address_country, order_billing_address_email, order_billing_address_first_name, order_billing_address_last_name, order_billing_address_phone, order_billing_address_postal_code, order_billing_address_state, order_cart_id, order_coupon, order_currency, order_discount, order_id, order_interval_frequency, order_interval_unit, order_order_id, order_products, order_revenue, order_status, order_subtotal, order_tax, order_total, order_type, order_value, products, sku_override, started_at, status, updated_at, user_id, original_timestamp, context_source, context_library_name, context_library_version, context_ip, event_id);

CREATE TABLE ecommerce.events_base_subscription_created
(
    charge_interval_frequency String,
    created_at String,
    has_queued_charges String,
    is_skippable String,
    is_swappable String,
    max_retries_reached String,
    next_charge_scheduled_at String,
    order_billing_address_address String,
    order_billing_address_city String,
    order_billing_address_country String,
    order_billing_address_email String,
    order_billing_address_first_name String,
    order_billing_address_last_name String,
    order_billing_address_phone String,
    order_billing_address_postal_code String,
    order_billing_address_state String,
    order_coupon String,
    order_currency String,
    order_discount String,
    order_id String,
    order_interval_frequency String,
    order_interval_unit String,
    order_order_id String,
    order_products String,
    order_revenue String,
    order_status String,
    order_subtotal String,
    order_tax String,
    order_total String,
    order_type String,
    order_value String,
    products String,
    sku_override String,
    started_at String,
    status String,
    updated_at String,
    user_id String,
    original_timestamp String,
    context_library_name String,
    context_ip String,
    context_source String,
    context_library_version String,
    event_id String,
) ENGINE = MergeTree ORDER BY (charge_interval_frequency, created_at, has_queued_charges, is_skippable, is_swappable, max_retries_reached, next_charge_scheduled_at, order_billing_address_address, order_billing_address_city, order_billing_address_country, order_billing_address_email, order_billing_address_first_name, order_billing_address_last_name, order_billing_address_phone, order_billing_address_postal_code, order_billing_address_state, order_coupon, order_currency, order_discount, order_id, order_interval_frequency, order_interval_unit, order_order_id, order_products, order_revenue, order_status, order_subtotal, order_tax, order_total, order_type, order_value, products, sku_override, started_at, status, updated_at, user_id, original_timestamp, context_library_name, context_ip, context_source, context_library_version, event_id);

CREATE TABLE ecommerce.events_base_tracks
(
    event String,
    event_text String,
    anonymous_id String,
    user_id String,
    original_timestamp String,
    context_source String,
    context_ip String,
    context_library_version String,
    context_library_name String,
    context_user_agent String,
    context_passed_ip String,
    context_locale String,
    event_id String,
) ENGINE = MergeTree ORDER BY (event, event_text, anonymous_id, user_id, original_timestamp, context_source, context_ip, context_library_version, context_library_name, context_user_agent, context_passed_ip, context_locale, event_id);

CREATE TABLE ecommerce.events_base_users
(
    address_city String,
    address_country_code String,
    address_postal_code String,
    address_state String,
    address_street String,
    addresses String,
    created_at String,
    email String,
    external_customer_id String,
    first_name String,
    last_name String,
    name String,
    phone String,
    anonymous_id String,
    user_id String,
    context_passed_ip String,
    context_traits_email String,
    context_traits_first_name String,
    context_library_name String,
    context_traits_phone String,
    context_user_agent String,
    context_source String,
    context_traits_external_customer_id String,
    context_traits_created_at String,
    context_traits_last_name String,
    context_locale String,
    context_library_version String,
    context_ip String,
    context_traits_address_country_code String,
    context_traits_name String,
    context_traits_address_city String,
    context_traits_context_anonymous_id String,
    context_traits_address_street String,
    context_traits_address_state String,
    context_traits_context_client_id String,
    context_traits_address_postal_code String,
    context_traits_context_ip String,
    context_traits_context_session_id String,
    context_traits_addresses String,
    context_traits_context_page_title String,
    context_page_width String,
    context_traits_context_page_url String,
    context_traits_context_referrer String,
    context_traits_context_os_name String,
    context_traits_context_locale String,
    context_page_referrer String,
    context_traits_context_library_name String,
    context_os_name String,
    context_page_path String,
    context_page_height String,
    context_traits_context_initialized String,
    context_page_search String,
    context_debug String,
    context_traits_context_app String,
    context_traits_context_page_referrer String,
    context_traits_context_page_search String,
    context_traits_context_library_version String,
    context_traits_context_debug String,
    context_traits_context_user_agent String,
    context_traits_context_timezone String,
    context_traits_context_offline String,
    context_traits_context_page_height String,
    context_timezone String,
    context_referrer String,
    context_traits_context_page_path String,
    context_page_title String,
    context_traits_context_page_width String,
    context_page_url String,
    context_campaign_gclid String,
    context_traits_context_campaign_gclid String,
    context_traits_context_page_hash String,
    context_page_hash String,
    context_traits_context_campaign_source String,
    context_campaign_term String,
    context_traits_context_campaign_name String,
    context_campaign_source String,
    context_traits_context_campaign_medium String,
    context_traits_context_campaign_term String,
    context_campaign_medium String,
    context_campaign_name String,
    context_campaign_profile String,
    context_traits_context_campaign_profile String,
    context_traits_context_campaign_id String,
    context_campaign_id String,
    context_traits_context_campaign_content String,
    context_campaign_content String,
) ENGINE = MergeTree ORDER BY (address_city, address_country_code, address_postal_code, address_state, address_street, addresses, created_at, email, external_customer_id, first_name, last_name, name, phone, anonymous_id, user_id, context_passed_ip, context_traits_email, context_traits_first_name, context_library_name, context_traits_phone, context_user_agent, context_source, context_traits_external_customer_id, context_traits_created_at, context_traits_last_name, context_locale, context_library_version, context_ip, context_traits_address_country_code, context_traits_name, context_traits_address_city, context_traits_context_anonymous_id, context_traits_address_street, context_traits_address_state, context_traits_context_client_id, context_traits_address_postal_code, context_traits_context_ip, context_traits_context_session_id, context_traits_addresses, context_traits_context_page_title, context_page_width, context_traits_context_page_url, context_traits_context_referrer, context_traits_context_os_name, context_traits_context_locale, context_page_referrer, context_traits_context_library_name, context_os_name, context_page_path, context_page_height, context_traits_context_initialized, context_page_search, context_debug, context_traits_context_app, context_traits_context_page_referrer, context_traits_context_page_search, context_traits_context_library_version, context_traits_context_debug, context_traits_context_user_agent, context_traits_context_timezone, context_traits_context_offline, context_traits_context_page_height, context_timezone, context_referrer, context_traits_context_page_path, context_page_title, context_traits_context_page_width, context_page_url, context_campaign_gclid, context_traits_context_campaign_gclid, context_traits_context_page_hash, context_page_hash, context_traits_context_campaign_source, context_campaign_term, context_traits_context_campaign_name, context_campaign_source, context_traits_context_campaign_medium, context_traits_context_campaign_term, context_campaign_medium, context_campaign_name, context_campaign_profile, context_traits_context_campaign_profile, context_traits_context_campaign_id, context_campaign_id, context_traits_context_campaign_content, context_campaign_content);

CREATE TABLE ecommerce.events_base_cart_line_items
(
    event_type String,
    event_id String,
    cart_id String,
    original_timestamp String,
    brand String,
    category String,
    imageurl String,
    name String,
    position String,
    price String,
    product_id String,
    quantity String,
    sku String,
    url String,
    variant String,
    unnested_product_column String,
) ENGINE = MergeTree ORDER BY (event_type, event_id, cart_id, original_timestamp, brand, category, imageurl, name, position, price, product_id, quantity, sku, url, variant, unnested_product_column);

CREATE TABLE ecommerce.events_base_checkout_line_items
(
    event_type String,
    event_id String,
    cart_id String,
    original_timestamp String,
    is_refunded String,
    line_item_id String,
    name String,
    position String,
    price String,
    product_id String,
    quantity String,
    sku String,
    variant String,
    unnested_product_column String,
) ENGINE = MergeTree ORDER BY (event_type, event_id, cart_id, original_timestamp, is_refunded, line_item_id, name, position, price, product_id, quantity, sku, variant, unnested_product_column);

CREATE TABLE ecommerce.events_base_order_line_items
(
    event_type String,
    order_id String,
    original_timestamp String,
    is_refunded String,
    line_item_id String,
    name String,
    position String,
    price String,
    product_id String,
    quantity String,
    sku String,
    variant String,
    unnested_product_column String,
) ENGINE = MergeTree ORDER BY (event_type, order_id, original_timestamp, is_refunded, line_item_id, name, position, price, product_id, quantity, sku, variant, unnested_product_column);

CREATE TABLE ecommerce.events_base_product_list_viewed_products
(
    event_type String,
    event_id String,
    original_timestamp String,
    list_id String,
    brand String,
    category String,
    imageurl String,
    name String,
    position String,
    price String,
    product_id String,
    quantity String,
    sku String,
    url String,
    variant String,
    unnested_product_column String,
) ENGINE = MergeTree ORDER BY (event_type, event_id, original_timestamp, list_id, brand, category, imageurl, name, position, price, product_id, quantity, sku, url, variant, unnested_product_column);